name: Python package

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Precommit
        run: |
          pip install pre-commit==2.19.*
          pre-commit run --all-files
      - name: Test with pytest
        run: |
          pip install coverage==6.3.3
          coverage run -m unittest
      - name: Coverage
        run: |
          coverage report
      - name: Publish PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine==4.0.1
          python setup.py bdist_wheel --universal
          python -m twine upload dist/* -uymil -p%PYPI_PASSWORD%
